// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RcloneAuthorize(arg1:string):Promise<string>;

export function RunSetup(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string):Promise<string>;
