// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyKDETheme(arg1) {
  return window['go']['main']['App']['ApplyKDETheme'](arg1);
}

export function RcloneAuthorize(arg1) {
  return window['go']['main']['App']['RcloneAuthorize'](arg1);
}

export function RunSetup(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunSetup'](arg1, arg2, arg3, arg4, arg5);
}
